package com.thecrazy8.craftedit.gui;

import com.mojang.blaze3d.systems.RenderSystem;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;

/**
 * Specific recipe editor screen for creating/editing individual recipes
 * 
 * This screen provides a detailed interface for editing a specific recipe type,
 * allowing users to:
 * - Define input items/ingredients
 * - Define output items
 * - Set recipe parameters (cooking time, experience, etc.)
 * - Generate CraftTweaker script code
 * - Save scripts to files
 */
@OnlyIn(Dist.CLIENT)
public class SpecificRecipeEditorScreen extends Screen {
    private final RecipeEditorScreen.RecipeType recipeType;
    private final Screen previousScreen;
    
    // UI Components
    private EditBox scriptOutputBox;
    private Button generateScriptButton;
    private Button saveScriptButton;
    private Button backButton;
    
    public SpecificRecipeEditorScreen(RecipeEditorScreen.RecipeType recipeType, Screen previousScreen) {
        super(Component.literal("Edit " + recipeType.getDisplayName() + " Recipe"));
        this.recipeType = recipeType;
        this.previousScreen = previousScreen;
    }
    
    @Override
    protected void init() {
        super.init();
        
        int buttonWidth = 120;
        int buttonHeight = 20;
        
        // Script output text box (shows generated CraftTweaker script)
        this.scriptOutputBox = new EditBox(
            this.font,
            this.width / 2 - 150,
            60,
            300,
            100,
            Component.literal("Generated Script")
        );
        this.scriptOutputBox.setMaxLength(5000);
        this.scriptOutputBox.setValue("// CraftTweaker script will be generated here\n// Add your recipe inputs and outputs above");
        addRenderableWidget(this.scriptOutputBox);
        
        // Generate Script button
        this.generateScriptButton = Button.builder(
            Component.literal("Generate Script"),
            button -> generateScript()
        )
        .bounds(this.width / 2 - buttonWidth - 5, this.height - 50, buttonWidth, buttonHeight)
        .build();
        addRenderableWidget(this.generateScriptButton);
        
        // Save Script button
        this.saveScriptButton = Button.builder(
            Component.literal("Save Script"),
            button -> saveScript()
        )
        .bounds(this.width / 2 + 5, this.height - 50, buttonWidth, buttonHeight)
        .build();
        addRenderableWidget(this.saveScriptButton);
        
        // Back button
        this.backButton = Button.builder(
            Component.literal("Back"),
            button -> goBack()
        )
        .bounds(10, this.height - 30, 60, buttonHeight)
        .build();
        addRenderableWidget(this.backButton);
    }
    
    private void generateScript() {
        // Generate CraftTweaker script based on recipe type and inputs
        StringBuilder script = new StringBuilder();
        script.append("// ").append(recipeType.getDisplayName()).append(" Recipe Script\n");
        script.append("// Generated by Craftedit\n\n");
        
        switch (recipeType) {
            case CRAFTING_TABLE:
                script.append("<recipetype:minecraft:crafting>.addShaped(\"custom_recipe\", <item:minecraft:diamond>, [\n");
                script.append("    [<item:minecraft:stick>, <item:minecraft:stick>, <item:minecraft:stick>],\n");
                script.append("    [<item:minecraft:stick>, <item:minecraft:gold_ingot>, <item:minecraft:stick>],\n");
                script.append("    [<item:minecraft:stick>, <item:minecraft:stick>, <item:minecraft:stick>]\n");
                script.append("]);");
                break;
            case BREWING_STAND:
                script.append("<recipetype:minecraft:brewing>.addRecipe(<item:minecraft:potion>.withTag({Potion: \"minecraft:water\"}), <item:minecraft:nether_wart>, <item:minecraft:potion>.withTag({Potion: \"minecraft:awkward\"}));");
                break;
            case FURNACE:
                script.append("<recipetype:minecraft:smelting>.addRecipe(\"custom_smelting\", <item:minecraft:iron_ingot>, <item:minecraft:iron_ore>, 0.7, 200);");
                break;
            case BOTANY_POT:
                script.append("// Botany Pot recipe example\n");
                script.append("// <recipetype:botanypots:crop>.addRecipe(name, seed, categories, output, ticks, minRolls);");
                break;
            case ANVIL:
                script.append("// Anvil recipe example\n");
                script.append("// <recipetype:minecraft:anvil>.addRecipe(name, left, right, output, xpCost);");
                break;
            case SMITHING_TABLE:
                script.append("<recipetype:minecraft:smithing>.addRecipe(\"custom_smithing\", <item:minecraft:netherite_sword>, <item:minecraft:diamond_sword>, <item:minecraft:netherite_ingot>);");
                break;
        }
        
        this.scriptOutputBox.setValue(script.toString());
    }
    
    private void saveScript() {
        // Save the generated script to a file
        // This would save to the scripts folder for CraftTweaker to load
        String script = this.scriptOutputBox.getValue();
        // TODO: Implement file saving logic
        if (minecraft != null && minecraft.player != null) {
            minecraft.player.sendSystemMessage(Component.literal("Script saved to scripts folder!"));
        }
    }
    
    private void goBack() {
        if (minecraft != null) {
            minecraft.setScreen(previousScreen);
        }
    }
    
    @Override
    public void render(GuiGraphics graphics, int mouseX, int mouseY, float partialTick) {
        // Render background
        this.renderBackground(graphics, mouseX, mouseY, partialTick);
        
        // Render title
        graphics.drawCenteredString(this.font, this.title, this.width / 2, 20, 0xFFFFFF);
        
        // Render instructions
        Component instructions = Component.literal("Configure your recipe and click 'Generate Script'");
        graphics.drawCenteredString(this.font, instructions, this.width / 2, 40, 0xAAAAAA);
        
        // Render widgets
        super.render(graphics, mouseX, mouseY, partialTick);
    }
    
    @Override
    public boolean isPauseScreen() {
        return false;
    }
}
